import { DM_Sans } from "next/font/google";
import { Providers } from "./providers";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "M4mba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={dmSans.className} >
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    
  );
}
